// source: proto/wrappers.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
goog.exportSymbol('proto.zdautomotive.protobuf.SERVICE_TYPE', null, global);
goog.exportSymbol('proto.zdautomotive.protobuf.ZDRequest', null, global);
goog.exportSymbol('proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption', null, global);
goog.exportSymbol('proto.zdautomotive.protobuf.ZDResponse', null, global);
goog.exportSymbol('proto.zdautomotive.protobuf.ZDResponse.ERROR_CODE', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.zdautomotive.protobuf.ZDRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.zdautomotive.protobuf.ZDRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.zdautomotive.protobuf.ZDRequest.displayName = 'proto.zdautomotive.protobuf.ZDRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption.displayName = 'proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.zdautomotive.protobuf.ZDResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.zdautomotive.protobuf.ZDResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.zdautomotive.protobuf.ZDResponse.displayName = 'proto.zdautomotive.protobuf.ZDResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.zdautomotive.protobuf.ZDRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.zdautomotive.protobuf.ZDRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.zdautomotive.protobuf.ZDRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.zdautomotive.protobuf.ZDRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    data: (f = msg.getData()) && google_protobuf_any_pb.Any.toObject(includeInstance, f),
    option: (f = msg.getOption()) && proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.zdautomotive.protobuf.ZDRequest}
 */
proto.zdautomotive.protobuf.ZDRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.zdautomotive.protobuf.ZDRequest;
  return proto.zdautomotive.protobuf.ZDRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.zdautomotive.protobuf.ZDRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.zdautomotive.protobuf.ZDRequest}
 */
proto.zdautomotive.protobuf.ZDRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.zdautomotive.protobuf.SERVICE_TYPE} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    case 3:
      var value = new proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption;
      reader.readMessage(value,proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption.deserializeBinaryFromReader);
      msg.setOption(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.zdautomotive.protobuf.ZDRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.zdautomotive.protobuf.ZDRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.zdautomotive.protobuf.ZDRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.zdautomotive.protobuf.ZDRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
  f = message.getOption();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption.prototype.toObject = function(opt_includeInstance) {
  return proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption.toObject = function(includeInstance, msg) {
  var f, obj = {
    timeout: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption}
 */
proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption;
  return proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption}
 */
proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTimeout(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimeout();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 timeout = 1;
 * @return {number}
 */
proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption.prototype.getTimeout = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption} returns this
 */
proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption.prototype.setTimeout = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional SERVICE_TYPE type = 1;
 * @return {!proto.zdautomotive.protobuf.SERVICE_TYPE}
 */
proto.zdautomotive.protobuf.ZDRequest.prototype.getType = function() {
  return /** @type {!proto.zdautomotive.protobuf.SERVICE_TYPE} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.zdautomotive.protobuf.SERVICE_TYPE} value
 * @return {!proto.zdautomotive.protobuf.ZDRequest} returns this
 */
proto.zdautomotive.protobuf.ZDRequest.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional google.protobuf.Any data = 2;
 * @return {?proto.google.protobuf.Any}
 */
proto.zdautomotive.protobuf.ZDRequest.prototype.getData = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 2));
};


/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.zdautomotive.protobuf.ZDRequest} returns this
*/
proto.zdautomotive.protobuf.ZDRequest.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.zdautomotive.protobuf.ZDRequest} returns this
 */
proto.zdautomotive.protobuf.ZDRequest.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.zdautomotive.protobuf.ZDRequest.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ZDRequestOption option = 3;
 * @return {?proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption}
 */
proto.zdautomotive.protobuf.ZDRequest.prototype.getOption = function() {
  return /** @type{?proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption} */ (
    jspb.Message.getWrapperField(this, proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption, 3));
};


/**
 * @param {?proto.zdautomotive.protobuf.ZDRequest.ZDRequestOption|undefined} value
 * @return {!proto.zdautomotive.protobuf.ZDRequest} returns this
*/
proto.zdautomotive.protobuf.ZDRequest.prototype.setOption = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.zdautomotive.protobuf.ZDRequest} returns this
 */
proto.zdautomotive.protobuf.ZDRequest.prototype.clearOption = function() {
  return this.setOption(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.zdautomotive.protobuf.ZDRequest.prototype.hasOption = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.zdautomotive.protobuf.ZDResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.zdautomotive.protobuf.ZDResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.zdautomotive.protobuf.ZDResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.zdautomotive.protobuf.ZDResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: jspb.Message.getFieldWithDefault(msg, 1, 0),
    message: jspb.Message.getFieldWithDefault(msg, 2, ""),
    data: (f = msg.getData()) && google_protobuf_any_pb.Any.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.zdautomotive.protobuf.ZDResponse}
 */
proto.zdautomotive.protobuf.ZDResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.zdautomotive.protobuf.ZDResponse;
  return proto.zdautomotive.protobuf.ZDResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.zdautomotive.protobuf.ZDResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.zdautomotive.protobuf.ZDResponse}
 */
proto.zdautomotive.protobuf.ZDResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.zdautomotive.protobuf.ZDResponse.ERROR_CODE} */ (reader.readEnum());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 3:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.zdautomotive.protobuf.ZDResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.zdautomotive.protobuf.ZDResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.zdautomotive.protobuf.ZDResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.zdautomotive.protobuf.ZDResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCode();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.zdautomotive.protobuf.ZDResponse.ERROR_CODE = {
  OK: 0,
  CLIENT_ERROR: 1,
  SERVER_ERROR: 2
};

/**
 * optional ERROR_CODE code = 1;
 * @return {!proto.zdautomotive.protobuf.ZDResponse.ERROR_CODE}
 */
proto.zdautomotive.protobuf.ZDResponse.prototype.getCode = function() {
  return /** @type {!proto.zdautomotive.protobuf.ZDResponse.ERROR_CODE} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.zdautomotive.protobuf.ZDResponse.ERROR_CODE} value
 * @return {!proto.zdautomotive.protobuf.ZDResponse} returns this
 */
proto.zdautomotive.protobuf.ZDResponse.prototype.setCode = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.zdautomotive.protobuf.ZDResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.zdautomotive.protobuf.ZDResponse} returns this
 */
proto.zdautomotive.protobuf.ZDResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Any data = 3;
 * @return {?proto.google.protobuf.Any}
 */
proto.zdautomotive.protobuf.ZDResponse.prototype.getData = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 3));
};


/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.zdautomotive.protobuf.ZDResponse} returns this
*/
proto.zdautomotive.protobuf.ZDResponse.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.zdautomotive.protobuf.ZDResponse} returns this
 */
proto.zdautomotive.protobuf.ZDResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.zdautomotive.protobuf.ZDResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * @enum {number}
 */
proto.zdautomotive.protobuf.SERVICE_TYPE = {
  SERVICE_SYS_CANCEL: 0,
  SERVICE_GET_CONFIG: 1,
  SERVICE_SET_CONFIG: 2,
  SERVICE_EXAMPLE_A: 3,
  SERVICE_EXAMPLE_B: 4,
  SERVICE_EXAMPLE_C: 5
};

goog.object.extend(exports, proto.zdautomotive.protobuf);
